# Generated by Django 4.0.2 on 2022-02-13 00:19

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=products.models.get_file_path)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.property')),
            ],
        ),
    ]
